linters:
  enable:
  - gofmt
  - nolintlint

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
  - path: _test\.go
    linters:
    - staticcheck
    text: "SA1019: tableprinter.NoHeader is deprecated: use WithHeader unless required otherwise."
