project_name: gh

release:
  prerelease: auto

before:
  hooks:
    - go mod tidy
builds:
  - binary: bin/gh
    main: ./cmd/gh
    ldflags:
      - -s -w -X github.com/cli/cli/command.Version={{.Version}} -X github.com/cli/cli/command.BuildDate={{time "2006-01-02"}}
      - -X github.com/cli/cli/context.oauthClientID={{.Env.GH_OAUTH_CLIENT_ID}}
      - -X github.com/cli/cli/context.oauthClientSecret={{.Env.GH_OAUTH_CLIENT_SECRET}}
      - -X main.updaterEnabled=github/homebrew-gh
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    replacements:
      darwin: macOS
    format: tar.gz
    format_overrides:
      - goos: windows
        format: binary

brews:
  - name: gh
    github:
      owner: github
      name: homebrew-gh
    skip_upload: auto
    description: GitHub CLI
    homepage: https://github.com/cli/cli
    custom_block: |
      head do
        url "https://github.com/cli/cli.git"
        depends_on "go"
      end
    install: |
      system "make" if build.head?
      bin.install "bin/gh"
      (bash_completion/"gh.sh").write `#{bin}/gh completion -s bash`
      (zsh_completion/"_gh").write `#{bin}/gh completion -s zsh`
    test: |
      help_text = shell_output("#{bin}/gh --help")
      assert_includes help_text, "Usage:"

nfpms:
  - license: MIT
    maintainer: GitHub
    homepage: https://github.com/cli/cli
    bindir: /usr/local
    dependencies:
      - git
    formats:
      - deb
      - rpm
