name: Go

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v21
      with:
        go-version: 1.15

    - name: Build
      run: go build vm ./...

    - name: Test
      run: go test vm ./...
