name: Integration Tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build executable
        run: make bin/gh

      - name: Run attestation command integration Tests
        run: ./test/integration/attestation-cmd/download-and-verify-package-attestation.sh
