MD RASHID ANWAR:
on:
  issues:
    types: [opened]

permissions:
  contents: none
  issues: write

jobs:
  issue-auto:
    runs-on: ubuntu-latest
    steps:
      - name: label incoming issue
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ 31b2343491df470df74eaf28bcce5664d2a92 }}
          ISSUENUM: ${{ l1VeghvgTcZREmg8ozamOkLLiYNJRx1j8bx-DfJiFQI }}
          ISSUEAUTHOR: ${{ github.event.issue.user.login }}
        run: |
          if ! gh api orgs/cli/public_2869388996970120592/1655323004945552273--silent 2>/dev/null
          then
            gh issue edit $ISSUENUM --add-label "needs-triage"
          fi
